Feature/swap eth references for avax and remove usd multiplication by price
pangolindex/analytics-avalanche pull request #19
Opened 2021-04-03 17:49 UTC by mdr223

In this PR I've swapped out all references of `eth` to be `avax` and I've also reverted to using the price information from the subgraph. This PR is blocked by a current PR to the subgraph repo: https://github.com/pangolindex/subgraph/pull/4.

These will need to be vetted and there are a couple TODOs that still need to be sorted out, particularly surrounding areas where I left in (or dropped) multiplying a variable by the `avaxPrice` because I was uncertain if the value being multiplied was supposed to be in AVAX or USD.

2021-04-03 19:38 UTC, HariSeldon23 commented on src/components/PositionList/index.js
> +    const valueUSD = poolOwnership * position.pair.reserveUSD
Shouldn't this be `const valueUSD = poolOwnership * position.pair.reserveUSD * avaxPrice`

2021-04-03 19:54 UTC, HariSeldon23 requested changes
Great that we're starting to work on this, as there's been a lot of comments in the community. 

My real concern at this stage is replacing Coingecko's pricing. AVAX will be priced across the market, so in terms of accuracy of the price point, I'd tend to trust CoinGecko over what is found on chain. 

This then raises the question of who are our target audience of the anayltics? Are our users expecting the price to match CoinGecko or are they expecting it to show them the on chain value to then use as an arbitrage opportunity.

I'd say people looking for arbitrage are probably sophisticated enough to get the on chain price themselves, so my take is that CoinGecko is probably the go to. 

However happy to discuss if I've missed something

2021-04-03 19:54 UTC, HariSeldon23 commented on src/contexts/GlobalData.js
> +  try {
I'm not sure if we should remove the CoinGecko price point. It's probably worth a wider discussion. So do we show the analytics with the most accurate data from Pangolin or do we keep the Coingecko price?

CoinGecko, I believe, gets price from numerous data points across all CEX's. So my take is that Coingecko probably has a more accurate real world price point.

2021-04-03 21:29 UTC, benber86 commented on src/components/TxnList/index.js
> +  }, [transactions, txFilter, avaxPrice])  // TODO: I think we can remove this? I don't think it gets used
I think it's needed to trigger the effect when avax price changes

2021-04-03 21:30 UTC, benber86 commented on src/contexts/TokenData.js
> +        const currentLiquidityUSD = data?.totalLiquidity * avaxPrice * data?.derivedAVAX  // TODO: do we need to remove this * avaxPrice
will check and report :)

2021-04-03 21:33 UTC, benber86 commented on src/pages/AccountPage.js
> +  }, [dynamicPositions])
`useMemo()` is also a hook. Do we really want to remove the ethPrice here ?
https://reactjs.org/docs/hooks-reference.html#usememo

2021-04-03 21:34 UTC, mdr223 commented on src/contexts/GlobalData.js
> -  }, [ethPrice, oldEthPrice, update, data, updateAllPairsInUniswap, updateAllTokensInUniswap])
I think this is also a hook? We might not want to remove this?

2021-04-03 21:35 UTC, benber86 requested changes
Great work, I'd double check the return arrays for the two hooks mentioned in my comments.

2021-04-03 21:35 UTC, benber86 commented on src/pages/AccountPage.js
> +  }, [dynamicPositions])
`useMemo()` is also a hook. Do we really want to remove the ethPrice here ?
https://reactjs.org/docs/hooks-reference.html#usememo

2021-04-03 21:40 UTC, benber86 commented on src/contexts/GlobalData.js
> -  }, [ethPrice, oldEthPrice, update, data, updateAllPairsInUniswap, updateAllTokensInUniswap])
yes, but if you've replaced `ethPrice` by `avaxPrice` and you need to update based on `oldEthPrice` anymore, I don't think  there will be any changes here.

2021-04-04 21:26 UTC, mdr223 commented on src/contexts/GlobalData.js
> +  try {
Copying some of the discussion from discord to github for visibility and posterity's sake. I definitely agree that Coingecko has a more accurate real world price point, however in order to clean up the analytics repo we need the USD values coming from our subgraph to actually be in terms of USD. To this effect, we needed to use the DAI/AVAX and USDT/AVAX pairs to price AVAX, since this is the only way to get this price (to my limited knowledge) in the subgraph.

Happy to discuss this more, at the moment I'm leaning towards swapping in our price point for Coingecko's simply because I think cleaning up our codebase is a must in order to facilitate growth and development in the short and long terms.

2021-04-04 21:42 UTC, mdr223 commented on src/components/TxnList/index.js
> +  }, [transactions, txFilter, avaxPrice])  // TODO: I think we can remove this? I don't think it gets used
Looking at the uniswap analytics version of this file (see: https://github.com/Uniswap/uniswap-info/blob/v2/src/components/TxnList/index.js) I think that we can safely remove the price from this component. I'm guessing that it was added because we needed to multiply some USD values by the `avaxPrice` in order to get their true USD values. It's possible that the price multiplications were omitted by error (or for some reason I'm not aware of).

2021-04-04 22:12 UTC, mdr223 commented on src/contexts/GlobalData.js
> -  }, [ethPrice, oldEthPrice, update, data, updateAllPairsInUniswap, updateAllTokensInUniswap])
Based on Uniswap's code, it looks like there was a multiplication we were missing in `getGlobalData` which caused me to believe that `oldAvaxPrice` wasn't needed. I'm adding the multiplication back and will be adding `oldAvaxPrice` back to the mix as well.

2021-04-04 22:14 UTC, mdr223 commented on src/contexts/TokenData.js
> +        const currentLiquidityUSD = data?.totalLiquidity * avaxPrice * data?.derivedAVAX  // TODO: do we need to remove this * avaxPrice
Based on our discussion in Discord, I believe that we are correct to multiply by the `avaxPrice` here as the reasoning goes that the right hand side of this equation is (liquidity in Token) * (USD/AVAX) * (AVAX/Token) which comes out to liquidity in USD. Thus, it does not seem like this was a case of us multiplying USD by price to get the true USD value, so we'll leave the multiplication as is.

2021-04-04 22:18 UTC, mdr223 commented on src/pages/AccountPage.js
> +  }, [dynamicPositions])
Looking at Uniswap once again (https://github.com/Uniswap/uniswap-info/blob/v2/src/pages/AccountPage.js), it looks like we added multiplication by `ethPrice` here and now that we're no longer doing this multiplication it should be safe to remove `ethPrice` from the hook.

2021-04-04 22:22 UTC, mdr223 commented on src/components/TradingviewChart/index.js
> +      value: parseFloat(entry[field]) * avaxPrice,  // TODO: is entry[field] already in USD?
Looks like we added multiplication on USD here since this is not present in Uniswap's analytics code: (https://github.com/Uniswap/uniswap-info/blob/v2/src/components/TradingviewChart/index.js); will remove this.

2021-04-13 16:21 UTC, kmcintyre commented
What's the state of this PR?

2021-04-13 16:30 UTC, mdr223 commented on src/contexts/GlobalData.js
> +  try {
Resolving this after our check of the "market price" vs. the stablecoin computed price.

2021-04-13 16:32 UTC, mdr223 commented
> What's the state of this PR?

This PR is ready to go once the associated change to the subgraph repo is merged (see: https://github.com/pangolindex/subgraph/pull/4). I believe that @dasconnor has deployed that branch to a graph node which we will be able to test this set of changes against. Assuming the graph node and this set of changes pass our checks then both can be merged.

2021-04-19 14:59 UTC, dasconnor reviewed
I found a few instances where I think we can use a database value instead of multiplying. I also tested this against this live subgraph: https://thegraph.com/explorer/subgraph/dasconnor/pangolin-historical-pricing. Unfortunately, the first page wouldn't load for me. Just swap that link out on the client.js page to test. Something about timestamp formatting? Lastly, there are a few new compiler warnings. Mind trying to remove those? Great work!

2021-04-19 14:59 UTC, dasconnor commented on src/contexts/GlobalData.js
> +      data.totalLiquidityUSD = data.totalLiquidityAVAX * avaxPrice
I think you can switch this to use totalLiquidityUSD instead of getting the price from coingecko

2021-04-19 14:59 UTC, dasconnor commented on src/contexts/GlobalData.js
> +          data.totalLiquidityAVAX * avaxPrice,
Again I would use totalLiquidityUSD here

2021-04-19 14:59 UTC, dasconnor commented on src/contexts/GlobalData.js
> +      let latestLiquidityUSD = data[0].totalLiquidityAVAX * avaxPrice
totalLiquidityUSD

2021-04-19 14:59 UTC, dasconnor commented on src/contexts/TokenData.js
> +        const currentLiquidityUSD = data?.totalLiquidity * avaxPrice * data?.derivedAVAX
use totalLiquidityUSD

2021-04-28 15:58 UTC, mdr223 commented
@dasconnor Pushed changes that should address the issues you raised in your last comment. We will want to revert/update the  subgraph link before merging though, as I've left in the one that you shared for now just to make it easier for you to pull and see my changes. The data on the analytics page(s) is all zero'ed out at the moment, but it looks like this is because the subgraph contains 0 for many fields. I'm not sure if this was expected?

2021-07-12 19:03 UTC, bmino commented
We have finally migrated our subgraph to use the appropriate USD data where it is specified!

I'm still quite interested in fixing the "eth" references to "avax." If you have some time, this PR would be quite appreciated :)

2021-07-12 22:06 UTC, kmcintyre commented
Those charts are going to be ugly

On Mon, Jul 12, 2021, 12:03 PM Brandon ***@***.***> wrote:

> We have finally migrated our subgraph to use the appropriate USD data
> where it is specified!
>
> I'm still quite interested in fixing the "eth" references to "avax." If
> you have some time, this PR would be quite appreciated :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pangolindex/analytics/pull/19#issuecomment-878520342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHYQHVV5GYT3CSGZDVBEDDTXM4BTANCNFSM42KO45FQ>
> .
>

2021-07-14 23:27 UTC, mdr223 commented
Hi @bmino!! Sorry I've been swamped with my full time job these last couple weeks, but I'd definitely be happy to help resolve these merge conflicts in the next few weeks. I'm also working on Aspen so my free time is tight, but I'll definitely share what time I have to help out!

2021-09-01 20:26 UTC, HariSeldon23 commented
Closing for now

2021-09-01 20:26 UTC, closed without merging