Add token info and add to Metamask button
pangolindex/analytics-avalanche pull request #54
Opened 2021-09-03 18:58 UTC by HariSeldon23

This PR will allow token information to be shown on the Analytics page as well as an Add to Metamask button.

@best-coder-NA not sure if we want to run some marketing around this or if you'd like the new social media manager to do that

2021-09-03 20:56 UTC, bmino commented
I wanna make sure I have a set block of time to actually review this. Took a quick look and saw some commented dead code that should be removed. Biggest concern is if there is an external api request being done repetitively or on re-render. We were getting rate limited using CMC very fast and it broke large pieces of functionality

2021-09-06 16:51 UTC, SarjuHansaliya requested changes

2021-09-06 16:51 UTC, SarjuHansaliya commented on src/contexts/TokenData.js
> +      data.marketCapUSD = coin.data.market_data.market_cap.usd
I think this type of nested field access is prune to failed. 
for e.g. in case of `data.announcementChannel` if some of the coin doesn't have announcementChannel url then `coin.data.links.announcement_url` will be undefined and `coin.data.links.announcement_url[0]` will make token page crash.

2021-09-06 16:51 UTC, SarjuHansaliya commented on src/contexts/TokenData.js
> +      getTokenData(tokenAddress, ethPrice, ethPriceOld).then((data) => {
@fstar1129 what if `ethPrice` changes, will that call `getTokenData` again ? if yes in that case we need to cache / reduce coingecko api calls.

2021-09-06 16:51 UTC, SarjuHansaliya commented
@bmino I have added my comments, please share your thoughts when you get a chance.

2021-09-07 00:44 UTC, fstar1129 commented on src/contexts/TokenData.js
> +      data.marketCapUSD = coin.data.market_data.market_cap.usd
https://github.com/pangolindex/analytics/pull/56
I created a PR.

2021-09-07 00:45 UTC, fstar1129 commented on src/contexts/TokenData.js
> +      getTokenData(tokenAddress, ethPrice, ethPriceOld).then((data) => {
https://github.com/pangolindex/analytics/pull/56
I created a PR to update it.

2021-09-09 06:39 UTC, SarjuHansaliya commented on src/contexts/TokenData.js
> +      getTokenData(tokenAddress, ethPrice, ethPriceOld).then((data) => {
added comment to your PR

2021-09-09 17:57 UTC, best-coder-NA commented
> This PR will allow token information to be shown on the Analytics page as well as an Add to Metamask button.
> 
> @best-coder-NA not sure if we want to run some marketing around this or if you'd like the new social media manager to do that

Yeah I'll write an article describing the new features of the analytics page to post when we go live

2021-09-14 04:39 UTC, bmino approved these changes

2021-09-14 04:46 UTC, SarjuHansaliya approved these changes

2021-09-14 04:52 UTC, merged