Feature/hector.add token info
pangolindex/analytics-avalanche pull request #56
Opened 2021-09-07 00:43 UTC by fstar1129

1. Added a empty array/null check for market stats data.
2. Update useEffect for reduce ext API call

2021-09-09 06:22 UTC, SarjuHansaliya requested changes

2021-09-09 06:22 UTC, SarjuHansaliya commented on src/contexts/TokenData.js
> +    // data.totalLiquidityUSD = currentLiquidityUSD
@fstar1129 I see you have commented all these but we are using this in `src/pages/TokenPage.js` so we can remove those field here.

2021-09-10 03:08 UTC, fstar1129 commented
@SarjuHansaliya , I updated this PR for reducing coingecko call when getting initial data.
It should solve multi call of coingecko when data won't change.

2021-09-10 13:41 UTC, SarjuHansaliya commented
@fstar1129 I believe there will be some issue in this implementation. for e.g. 2nd useEffect is dependant on `ethPrice, ethPriceOld` so whenever those value changes, it will call `getTokenData` but getTokenData data doesn't have any coingecko related data so final tokenData will not have those data.

I think we can make this more better by creating a memoized hook whose sole responsibility is to get Coin data from CoinGecko. that you can use in src/pages/TokenPage.js separately. 

what do you think @bmino ?

2021-09-13 13:17 UTC, SarjuHansaliya commented
I have handled this in #62 , so closing this now.

2021-09-13 13:17 UTC, closed without merging